version: '3.3'

services:
  public-website:
    build:
      context: ./src/Frontend/PublicWebsite
      dockerfile: ../../../Dockerfile.frontend
      args:
        REACT_APP_API_URL: ${VITE_API_BASE_URL_TEST}/api
    container_name: batuara-public-website
    restart: unless-stopped
    ports:
      - "8003:80"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  admin-dashboard:
    build:
      context: ./src/Frontend/AdminDashboard
      dockerfile: ../../../Dockerfile.frontend
      args:
        REACT_APP_API_URL: ${VITE_API_BASE_URL_TEST}/api
    container_name: batuara-admin-dashboard
    restart: unless-stopped
    ports:
      - "8004:80"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"